language: php

sudo: false

env:
  - REPO_OWNER: $(dirname $TRAVIS_REPO_SLUG)


# This "ignore" directive travis from processing branches with
# a -built suffix, thus avoiding endless loops
# REQUIRED: If you're amended an existing config, the following
# two lines are required.
# if: branch =~ ^.*(?<!-built)$

before_install: 
- wget https://raw.githubusercontent.com/Automattic/vip-go-ci/master/tools-init.sh -O tools-init.sh 

# @TODO: Configure build steps
# before_script:
# - run: npm install
# - run: npm run build

# If you specify `script` directive, Travis will try to run PHPUnit
# Replace this with whatever tests you wish, or leave in place if
# you only want to run the deploy.
script: 
- bash tools-init.sh
- rm -f tools-init.sh
- cd ~/vip-go-ci-tools/vip-go-ci/
- ls -la
- ~/vip-go-ci-tools/vip-go-ci/vip-go-ci.php --repo-owner=fclaussen --repo-name=test-vip-go-ci --commit=$TRAVIS_COMMIT --token=32800bd2199e9a68f89b4e7c2985a7c70f5d4fb9 --phpcs-path=$HOME/vip-go-ci-tools/phpcs/bin/phpcs --phpcs=true --lint=true

# If you want to only run the deploy script when tests pass,
# use `after_success` instead, you will need to add a `script`
# directive with some tests if you want to do this :)
# REQUIRED: If you're amended an existing config, the following
# two lines are required.
# after_script:
#   - bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy-travis-prepare.sh") && bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")