version: 2
jobs:
  build:
    docker:
      # Pick a base image which matches the version of Node you need for
      # building from https://hub.docker.com/r/circleci/node/tags/
      #
      # Note: If using a different container, make sure it contains at least
      # git 2.6.0. (Use -stretch for circleci/node containers.)
      - image: circleci/php:7.2-stretch-node

    branches:
      # Don't build from a branch with the `-built` suffix, to
      # prevent endless loops of deploy scripts.
      # REQUIRED: If you're amended an existing config, the below are two
      # of the required lines you must add
      ignore:
        - /^.*-built$/
      only:
        - master
        - develop

    steps:
      - checkout

      # Configure build steps
      - run:
        name: 'Install vip-go-ci'
        command: |
          wget https://raw.githubusercontent.com/Automattic/vip-go-ci/master/tools-init.sh -O tools-init.sh && bash tools-init.sh && rm -f tools-init.sh

      - run: 'ls -la'

      # Uncomment this and supply your ssh fingerprint to enable CircleCI to push the built branch to GitHub
      # - add_ssh_keys:
      #    fingerprints:
      #      - "db:a5:26:f7:5d:f8:00:f9:07:fc:95:8b:6a:f9:11:f2"
